import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Virtual Shadi</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <h1>Hello</h1>
    </div>
  );
}
