import { useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import NavBar from "../components/NavBar";
import EventsList from "../components/EventsList";

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    // const token = localStorage.getItem("token");
    // token === null ? router.push("/auth") : null;
  }, []);

  return (
    <div>
      <Head>
        <title>Virtual Shadi</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <NavBar />
      <EventsList />
    </div>
  );
}
